--
-- PostgreSQL database dump
--

\restrict uqth3720LfFFRdF1pGsn2oPX1gbLpkZTkNsQhaeOCdB3DkV4SyC5OCGbOF6OGir

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-12-08 09:05:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 28592)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    direccion character varying(255),
    email character varying(255),
    nombre character varying(255),
    telefono character varying(255),
    tipo character varying(255)
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 28591)
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 28633)
-- Name: detalle_venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_venta (
    id bigint NOT NULL,
    cantidad integer,
    nombre_producto character varying(255),
    precio_unitario double precision,
    subtotal double precision,
    venta_id bigint
);


ALTER TABLE public.detalle_venta OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 28632)
-- Name: detalle_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 28600)
-- Name: detalles_venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_venta (
    id bigint NOT NULL,
    cantidad integer,
    nombre_producto character varying(255),
    precio_unitario double precision,
    producto_id bigint,
    subtotal double precision,
    venta_id bigint
);


ALTER TABLE public.detalles_venta OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 28599)
-- Name: detalles_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalles_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalles_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 28606)
-- Name: gastos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gastos (
    id bigint NOT NULL,
    categoria character varying(255),
    descripcion character varying(255),
    fecha character varying(255),
    valor double precision
);


ALTER TABLE public.gastos OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 28605)
-- Name: gastos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gastos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gastos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 28614)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    nombre character varying(255),
    precio double precision,
    stock integer
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 28613)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 28620)
-- Name: ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ventas (
    id bigint NOT NULL,
    cliente character varying(255),
    fecha character varying(255),
    metodo_pago character varying(255),
    total double precision
);


ALTER TABLE public.ventas OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 28619)
-- Name: ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ventas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4927 (class 0 OID 28592)
-- Dependencies: 218
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (id, direccion, email, nombre, telefono, tipo) FROM stdin;
1	Cúcuta	maria@example.com	Maria Perez	3001234567	Frecuente
\.


--
-- TOC entry 4937 (class 0 OID 28633)
-- Dependencies: 228
-- Data for Name: detalle_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_venta (id, cantidad, nombre_producto, precio_unitario, subtotal, venta_id) FROM stdin;
\.


--
-- TOC entry 4929 (class 0 OID 28600)
-- Dependencies: 220
-- Data for Name: detalles_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalles_venta (id, cantidad, nombre_producto, precio_unitario, producto_id, subtotal, venta_id) FROM stdin;
1	15	Cuaderno Grande	8000	2	120000	1
2	5	Lapicero Azul	2500	1	12500	2
\.


--
-- TOC entry 4931 (class 0 OID 28606)
-- Dependencies: 222
-- Data for Name: gastos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gastos (id, categoria, descripcion, fecha, valor) FROM stdin;
1	Internet	factura del internet mensual	2025-12-08	70000
\.


--
-- TOC entry 4933 (class 0 OID 28614)
-- Dependencies: 224
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productos (id, nombre, precio, stock) FROM stdin;
1	Lapicero Azul	2500	50
2	Cuaderno Grande	8000	20
\.


--
-- TOC entry 4935 (class 0 OID 28620)
-- Dependencies: 226
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ventas (id, cliente, fecha, metodo_pago, total) FROM stdin;
1	Alexis	2025-12-05	Efectivo	120000
2	Mostrador	2025-12-08	Nequi	12500
\.


--
-- TOC entry 4943 (class 0 OID 0)
-- Dependencies: 217
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_id_seq', 1, true);


--
-- TOC entry 4944 (class 0 OID 0)
-- Dependencies: 227
-- Name: detalle_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_venta_id_seq', 1, false);


--
-- TOC entry 4945 (class 0 OID 0)
-- Dependencies: 219
-- Name: detalles_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_venta_id_seq', 2, true);


--
-- TOC entry 4946 (class 0 OID 0)
-- Dependencies: 221
-- Name: gastos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gastos_id_seq', 1, true);


--
-- TOC entry 4947 (class 0 OID 0)
-- Dependencies: 223
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_seq', 2, true);


--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 225
-- Name: ventas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ventas_id_seq', 2, true);


--
-- TOC entry 4768 (class 2606 OID 28598)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- TOC entry 4778 (class 2606 OID 28637)
-- Name: detalle_venta detalle_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT detalle_venta_pkey PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 28604)
-- Name: detalles_venta detalles_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_venta
    ADD CONSTRAINT detalles_venta_pkey PRIMARY KEY (id);


--
-- TOC entry 4772 (class 2606 OID 28612)
-- Name: gastos gastos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gastos
    ADD CONSTRAINT gastos_pkey PRIMARY KEY (id);


--
-- TOC entry 4774 (class 2606 OID 28618)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 28626)
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 28627)
-- Name: detalles_venta fk453xcyfk9n6snv6qnjlo0p65p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_venta
    ADD CONSTRAINT fk453xcyfk9n6snv6qnjlo0p65p FOREIGN KEY (venta_id) REFERENCES public.ventas(id);


--
-- TOC entry 4780 (class 2606 OID 28638)
-- Name: detalle_venta fk834rjd9cwo349m5xdf1knbl0l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fk834rjd9cwo349m5xdf1knbl0l FOREIGN KEY (venta_id) REFERENCES public.ventas(id);


-- Completed on 2025-12-08 09:05:04

--
-- PostgreSQL database dump complete
--

\unrestrict uqth3720LfFFRdF1pGsn2oPX1gbLpkZTkNsQhaeOCdB3DkV4SyC5OCGbOF6OGir

